/* Assignment Operators
=
+=
-=
*=
%=
/=
**=

*/



// =
let b = 23; // =



// +=
let a = 12;
a +=4; //a = a + 4
console.log("a =",a);


//-=
let c = 12;
c -=4; //c = c - 4
console.log("c =",c);


// *=
let d = 12;
d *= 4; //d = d * 4
console.log("d =",d);



// %=
let e = 12;
e %= 4; //e = e * 4
console.log("e =",e);


// /=
let f = 12;
f /= 4; //f = f / 4
console.log("f =",f);


// **=
let g = 5;
g **= 4; //g = g **= 4
console.log("g =",g);

